import { fetchPlayers } from "../../services/fifa-api";

export type PlayerHint = {
  age: number;
  club: string;
  country: string;
  position: string;
  trivia: string;
};

export type PlayerRow = {
  name: string;
  meta: { shortened: boolean; fullName?: string };
  hint: PlayerHint;
};

export async function fetchPlayersFromAPI(): Promise<PlayerRow[]> {
  const res = await fetchPlayers();
  if (!res.ok) throw new Error(`Failed to fetch players: ${res.status}`);
  const json = await res.json();
  const rows: unknown[] = json.data ?? [];
  return rows.map((r: any) => ({
    name: r.name,
    meta: {
      shortened: Boolean(r.is_shortened),
      ...(r.full_name ? { fullName: r.full_name } : {}),
    },
    hint: {
      age: r.age,
      club: r.club,
      country: r.country,
      position: r.position,
      trivia: r.trivia,
    },
  }));
}

export const players: PlayerRow[] = [
  { name:"MESSI", meta:{shortened:false}, hint:{age:36,club:"Inter Miami",country:"Argentina",position:"FW",trivia:"World Cup 2022 winner"} },
  { name:"RONAL", meta:{shortened:true,fullName:"Cristiano Ronaldo"}, hint:{age:39,club:"Al Nassr",country:"Portugal",position:"FW",trivia:"All-time top scorer"} },
  { name:"RAMOS", meta:{shortened:false}, hint:{age:38,club:"Sevilla",country:"Spain",position:"CB",trivia:"Clutch goals"} },
  { name:"ROBEN", meta:{shortened:false}, hint:{age:40,club:"Retired",country:"Netherlands",position:"RW",trivia:"Cut inside legend"} },
  { name:"NEUER", meta:{shortened:false}, hint:{age:38,club:"Bayern Munich",country:"Germany",position:"GK",trivia:"Sweeper keeper"} },
  { name:"PIQUE", meta:{shortened:false}, hint:{age:37,club:"Retired",country:"Spain",position:"CB",trivia:"Barcelona legend"} },
  { name:"SUARE", meta:{shortened:true,fullName:"Suarez"}, hint:{age:37,club:"Inter Miami",country:"Uruguay",position:"ST",trivia:"Elite striker"} },
  { name:"MODRI", meta:{shortened:true,fullName:"Modric"}, hint:{age:38,club:"Real Madrid",country:"Croatia",position:"CM",trivia:"Ballon d'Or winner"} },
  { name:"BENZE", meta:{shortened:true,fullName:"Benzema"}, hint:{age:36,club:"Al Ittihad",country:"France",position:"ST",trivia:"Ballon d'Or 2022"} },
  { name:"LEWAN", meta:{shortened:true,fullName:"Lewandowski"}, hint:{age:35,club:"Barcelona",country:"Poland",position:"ST",trivia:"5 goals in 9 minutes"} },
  { name:"CAVAN", meta:{shortened:true,fullName:"Cavani"}, hint:{age:37,club:"Boca Juniors",country:"Uruguay",position:"ST",trivia:"El Matador"} },
  { name:"AGUER", meta:{shortened:true,fullName:"Aguero"}, hint:{age:35,club:"Retired",country:"Argentina",position:"ST",trivia:"93:20"} },
  { name:"SILVA", meta:{shortened:false}, hint:{age:38,club:"Real Sociedad",country:"Spain",position:"CM",trivia:"Playmaker"} },
  { name:"INIES", meta:{shortened:true,fullName:"Iniesta"}, hint:{age:39,club:"Retired",country:"Spain",position:"CM",trivia:"World Cup hero"} },
  { name:"XAVI", meta:{shortened:false}, hint:{age:44,club:"Retired",country:"Spain",position:"CM",trivia:"Barcelona legend"} },
  { name:"CHIEL", meta:{shortened:true,fullName:"Chiellini"}, hint:{age:39,club:"Retired",country:"Italy",position:"CB",trivia:"Italian wall"} },
  { name:"BONUC", meta:{shortened:true,fullName:"Bonucci"}, hint:{age:36,club:"Fenerbahce",country:"Italy",position:"CB",trivia:"Euro 2020 winner"} },
  { name:"ALVES", meta:{shortened:false}, hint:{age:40,club:"Retired",country:"Brazil",position:"RB",trivia:"Most titles"} },
  { name:"LAHM", meta:{shortened:false}, hint:{age:40,club:"Retired",country:"Germany",position:"RB",trivia:"WC captain"} },
  { name:"KEVIN", meta:{shortened:false,fullName:"Kevin De Bruyne"}, hint:{age:32,club:"Man City",country:"Belgium",position:"CM",trivia:"Assist king"} },
  { name:"SALAH", meta:{shortened:false}, hint:{age:31,club:"Liverpool",country:"Egypt",position:"RW",trivia:"Egyptian King"} },
  { name:"MBAPP", meta:{shortened:true,fullName:"Mbappe"}, hint:{age:25,club:"PSG",country:"France",position:"FW",trivia:"World Cup winner at 19"} },
  { name:"HAALA", meta:{shortened:true,fullName:"Haaland"}, hint:{age:23,club:"Man City",country:"Norway",position:"ST",trivia:"Premier League record scorer"} },
  { name:"KANE", meta:{shortened:false}, hint:{age:30,club:"Bayern Munich",country:"England",position:"ST",trivia:"England all-time top scorer"} },
  { name:"DEBRU", meta:{shortened:true,fullName:"De Bruyne"}, hint:{age:32,club:"Man City",country:"Belgium",position:"CM",trivia:"Assist king"} },
  { name:"VINIJ", meta:{shortened:true,fullName:"Vinicius Jr"}, hint:{age:23,club:"Real Madrid",country:"Brazil",position:"LW",trivia:"UCL final goalscorer"} },
  { name:"BELLI", meta:{shortened:true,fullName:"Bellingham"}, hint:{age:20,club:"Real Madrid",country:"England",position:"CM",trivia:"Golden Boy 2023"} },
  { name:"PEDRI", meta:{shortened:false}, hint:{age:21,club:"Barcelona",country:"Spain",position:"CM",trivia:"Golden Boy 2021"} },
  { name:"GAVI", meta:{shortened:false}, hint:{age:19,club:"Barcelona",country:"Spain",position:"CM",trivia:"Golden Boy 2022"} },
  { name:"FODEN", meta:{shortened:false}, hint:{age:23,club:"Man City",country:"England",position:"CM",trivia:"Man City academy"} },
  { name:"RODRI", meta:{shortened:false}, hint:{age:27,club:"Man City",country:"Spain",position:"CDM",trivia:"UCL final hero"} },
  { name:"RICE", meta:{shortened:false}, hint:{age:25,club:"Arsenal",country:"England",position:"CDM",trivia:"British record transfer"} },
  { name:"OSIMH", meta:{shortened:true,fullName:"Osimhen"}, hint:{age:25,club:"Napoli",country:"Nigeria",position:"ST",trivia:"Serie A top scorer"} },
  { name:"LAUTA", meta:{shortened:true,fullName:"Lautaro"}, hint:{age:26,club:"Inter",country:"Argentina",position:"ST",trivia:"World Cup winner"} },
  { name:"ALVAR", meta:{shortened:true,fullName:"Alvarez"}, hint:{age:24,club:"Man City",country:"Argentina",position:"FW",trivia:"World Cup winner"} },
  { name:"MUSIA", meta:{shortened:true,fullName:"Musiala"}, hint:{age:21,club:"Bayern",country:"Germany",position:"AM",trivia:"Dribbling wizard"} },
  { name:"WIRTZ", meta:{shortened:false}, hint:{age:20,club:"Leverkusen",country:"Germany",position:"AM",trivia:"Bundesliga breakout"} },
  { name:"SAKA", meta:{shortened:false}, hint:{age:22,club:"Arsenal",country:"England",position:"RW",trivia:"Academy star"} },
  { name:"RASHF", meta:{shortened:true,fullName:"Rashford"}, hint:{age:26,club:"Man United",country:"England",position:"LW",trivia:"Academy graduate"} },
  { name:"OEDEG", meta:{shortened:true,fullName:"Odegaard"}, hint:{age:25,club:"Arsenal",country:"Norway",position:"CM",trivia:"Youngest debut"} },
  { name:"FELIX", meta:{shortened:false}, hint:{age:24,club:"Barcelona",country:"Portugal",position:"FW",trivia:"Golden Boy 2019"} },
  { name:"LEAO", meta:{shortened:false}, hint:{age:24,club:"AC Milan",country:"Portugal",position:"LW",trivia:"Scudetto winner"} },
  { name:"KVARA", meta:{shortened:true,fullName:"Kvaratskhelia"}, hint:{age:23,club:"Napoli",country:"Georgia",position:"LW",trivia:"Georgian sensation"} },
  { name:"ENZO", meta:{shortened:false}, hint:{age:23,club:"Chelsea",country:"Argentina",position:"CM",trivia:"World Cup Young POTY"} },
  { name:"CAICE", meta:{shortened:true,fullName:"Caicedo"}, hint:{age:22,club:"Chelsea",country:"Ecuador",position:"CDM",trivia:"British record"} },
  { name:"MACAL", meta:{shortened:true,fullName:"Mac Allister"}, hint:{age:25,club:"Liverpool",country:"Argentina",position:"CM",trivia:"World Cup winner"} },
  { name:"SZOBO", meta:{shortened:true,fullName:"Szoboszlai"}, hint:{age:23,club:"Liverpool",country:"Hungary",position:"CM",trivia:"Hungarian captain"} },
  { name:"GRIEZ", meta:{shortened:true,fullName:"Griezmann"}, hint:{age:33,club:"Atletico",country:"France",position:"CF",trivia:"World Cup winner"} },
  { name:"DEMBE", meta:{shortened:true,fullName:"Dembele"}, hint:{age:26,club:"PSG",country:"France",position:"RW",trivia:"Dribble king"} },
  { name:"COMAN", meta:{shortened:false}, hint:{age:27,club:"Bayern",country:"France",position:"LW",trivia:"UCL final winner"} },
  { name:"VVD", meta:{shortened:false}, hint:{age:32,club:"Liverpool",country:"Netherlands",position:"CB",trivia:"Ballon d'Or runner-up"} },
  { name:"RUDIG", meta:{shortened:true,fullName:"Rudiger"}, hint:{age:31,club:"Real Madrid",country:"Germany",position:"CB",trivia:"Intense defender"} },
  { name:"MILIT", meta:{shortened:true,fullName:"Militao"}, hint:{age:26,club:"Real Madrid",country:"Brazil",position:"CB",trivia:"Brazil starter"} },
  { name:"ARAUJ", meta:{shortened:true,fullName:"Araujo"}, hint:{age:25,club:"Barcelona",country:"Uruguay",position:"CB",trivia:"Physical beast"} },
  { name:"KOUND", meta:{shortened:true,fullName:"Kounde"}, hint:{age:25,club:"Barcelona",country:"France",position:"CB",trivia:"Versatile defender"} },
  { name:"SALIB", meta:{shortened:true,fullName:"Saliba"}, hint:{age:23,club:"Arsenal",country:"France",position:"CB",trivia:"Young wall"} },
  { name:"GABRI", meta:{shortened:true,fullName:"Gabriel"}, hint:{age:26,club:"Arsenal",country:"Brazil",position:"CB",trivia:"Set piece threat"} },
  { name:"DIAS", meta:{shortened:false}, hint:{age:26,club:"Man City",country:"Portugal",position:"CB",trivia:"PL Player of the Season"} },
  { name:"STONE", meta:{shortened:true,fullName:"Stones"}, hint:{age:29,club:"Man City",country:"England",position:"CB",trivia:"Ball-playing CB"} },
  { name:"AKANJ", meta:{shortened:true,fullName:"Akanji"}, hint:{age:28,club:"Man City",country:"Switzerland",position:"CB",trivia:"Versatile"} },
  { name:"KIM", meta:{shortened:false}, hint:{age:27,club:"Bayern",country:"Korea",position:"CB",trivia:"Serie A Best Defender"} },
  { name:"UPAME", meta:{shortened:true,fullName:"Upamecano"}, hint:{age:25,club:"Bayern",country:"France",position:"CB",trivia:"Strong tackler"} },
  { name:"THEO", meta:{shortened:false}, hint:{age:26,club:"AC Milan",country:"France",position:"LB",trivia:"Fastest fullback"} },
  { name:"DAVIS", meta:{shortened:false}, hint:{age:23,club:"Bayern",country:"Canada",position:"LB",trivia:"Speed demon"} },
  { name:"CANCE", meta:{shortened:true,fullName:"Cancelo"}, hint:{age:29,club:"Barcelona",country:"Portugal",position:"RB",trivia:"Attacking fullback"} },
  { name:"WALKR", meta:{shortened:true,fullName:"Walker"}, hint:{age:33,club:"Man City",country:"England",position:"RB",trivia:"Speedster"} },
  { name:"TRENT", meta:{shortened:false}, hint:{age:25,club:"Liverpool",country:"England",position:"RB",trivia:"Assist record"} },
  { name:"ROBER", meta:{shortened:true,fullName:"Robertson"}, hint:{age:30,club:"Liverpool",country:"Scotland",position:"LB",trivia:"Scottish captain"} },
  { name:"HAKIM", meta:{shortened:true,fullName:"Hakimi"}, hint:{age:25,club:"PSG",country:"Morocco",position:"RB",trivia:"Fastest player"} },
  { name:"MENDY", meta:{shortened:false}, hint:{age:28,club:"Real Madrid",country:"France",position:"LB",trivia:"UCL winner"} },
  { name:"COURT", meta:{shortened:true,fullName:"Courtois"}, hint:{age:31,club:"Real Madrid",country:"Belgium",position:"GK",trivia:"UCL final MVP"} },
  { name:"ALISS", meta:{shortened:true,fullName:"Alisson"}, hint:{age:31,club:"Liverpool",country:"Brazil",position:"GK",trivia:"Scoring GK"} },
  { name:"EDERS", meta:{shortened:true,fullName:"Ederson"}, hint:{age:30,club:"Man City",country:"Brazil",position:"GK",trivia:"Ball-playing GK"} },
  { name:"DONNA", meta:{shortened:true,fullName:"Donnarumma"}, hint:{age:25,club:"PSG",country:"Italy",position:"GK",trivia:"Euro 2020 hero"} },
  { name:"OBLAK", meta:{shortened:false}, hint:{age:31,club:"Atletico",country:"Slovenia",position:"GK",trivia:"Top GK"} },
  { name:"MAIGN", meta:{shortened:true,fullName:"Maignan"}, hint:{age:28,club:"AC Milan",country:"France",position:"GK",trivia:"Serie A champion"} },
  { name:"TERST", meta:{shortened:true,fullName:"Ter Stegen"}, hint:{age:31,club:"Barcelona",country:"Germany",position:"GK",trivia:"Sweeper keeper"} },
  { name:"ONANA", meta:{shortened:false}, hint:{age:27,club:"Man United",country:"Cameroon",position:"GK",trivia:"Ball-playing GK"} },
  { name:"RAMSD", meta:{shortened:true,fullName:"Ramsdale"}, hint:{age:25,club:"Arsenal",country:"England",position:"GK",trivia:"Reactions"} },
  { name:"POPEI", meta:{shortened:true,fullName:"Pope"}, hint:{age:31,club:"Newcastle",country:"England",position:"GK",trivia:"Clean sheets"} },
  { name:"MARTI", meta:{shortened:true,fullName:"Martinez"}, hint:{age:31,club:"Aston Villa",country:"Argentina",position:"GK",trivia:"World Cup hero"} },
  { name:"NAVAS", meta:{shortened:false}, hint:{age:37,club:"PSG",country:"Costa Rica",position:"GK",trivia:"UCL winner"} },
  { name:"SOMME", meta:{shortened:true,fullName:"Sommer"}, hint:{age:35,club:"Inter",country:"Switzerland",position:"GK",trivia:"Reliable"} },
  { name:"KROOS", meta:{shortened:false}, hint:{age:34,club:"Real Madrid",country:"Germany",position:"CM",trivia:"Passing master"} },
  { name:"POGBA", meta:{shortened:false}, hint:{age:31,club:"Juventus",country:"France",position:"CM",trivia:"World Cup winner"} },
  { name:"KANTE", meta:{shortened:false}, hint:{age:33,club:"Al Ittihad",country:"France",position:"CDM",trivia:"Leicester miracle"} },
  { name:"CASEM", meta:{shortened:true,fullName:"Casemiro"}, hint:{age:32,club:"Man United",country:"Brazil",position:"CDM",trivia:"UCL winner"} },
  { name:"FABIN", meta:{shortened:true,fullName:"Fabinho"}, hint:{age:30,club:"Al Ittihad",country:"Brazil",position:"CDM",trivia:"Tackle machine"} },
  { name:"FERNA", meta:{shortened:true,fullName:"Fernandinho"}, hint:{age:38,club:"Retired",country:"Brazil",position:"CDM",trivia:"Man City legend"} },
  { name:"VERRA", meta:{shortened:true,fullName:"Verratti"}, hint:{age:31,club:"Al Arabi",country:"Italy",position:"CM",trivia:"Mini Pirlo"} },
  { name:"BRUNO", meta:{shortened:false}, hint:{age:29,club:"Man United",country:"Portugal",position:"CM",trivia:"Penalty king"} },
  { name:"BERNA", meta:{shortened:true,fullName:"Bernardo"}, hint:{age:29,club:"Man City",country:"Portugal",position:"CM",trivia:"Workhorse"} },
  { name:"KOVAC", meta:{shortened:true,fullName:"Kovacic"}, hint:{age:29,club:"Man City",country:"Croatia",position:"CM",trivia:"Dribbler"} },
  { name:"GUNDO", meta:{shortened:true,fullName:"Gundogan"}, hint:{age:33,club:"Barcelona",country:"Germany",position:"CM",trivia:"UCL final goals"} },
  { name:"THIAG", meta:{shortened:true,fullName:"Thiago"}, hint:{age:33,club:"Liverpool",country:"Spain",position:"CM",trivia:"Technical genius"} },
  { name:"XHAKA", meta:{shortened:false}, hint:{age:31,club:"Leverkusen",country:"Switzerland",position:"CM",trivia:"Swiss captain"} },
  { name:"MOUNT", meta:{shortened:false}, hint:{age:25,club:"Man United",country:"England",position:"CM",trivia:"Chelsea academy"} },
  { name:"GALLI", meta:{shortened:true,fullName:"Gallagher"}, hint:{age:24,club:"Chelsea",country:"England",position:"CM",trivia:"Work rate"} },
  { name:"MADDI", meta:{shortened:true,fullName:"Maddison"}, hint:{age:27,club:"Tottenham",country:"England",position:"AM",trivia:"Set piece specialist"} },
  { name:"EZE", meta:{shortened:false}, hint:{age:25,club:"Crystal Palace",country:"England",position:"AM",trivia:"Dribbling"} },
  { name:"OLMO", meta:{shortened:false}, hint:{age:25,club:"RB Leipzig",country:"Spain",position:"AM",trivia:"Euro 2024 star"} },
  { name:"NUNEZ", meta:{shortened:false}, hint:{age:24,club:"Liverpool",country:"Uruguay",position:"ST",trivia:"Chaos factor"} },
  { name:"JULIA", meta:{shortened:true,fullName:"Julian"}, hint:{age:24,club:"Man City",country:"Argentina",position:"FW",trivia:"World Cup winner"} },
  { name:"DAVID", meta:{shortened:false}, hint:{age:24,club:"Lille",country:"Canada",position:"ST",trivia:"Canadian star"} },
  { name:"OPEND", meta:{shortened:true,fullName:"Openda"}, hint:{age:24,club:"RB Leipzig",country:"Belgium",position:"ST",trivia:"Pace"} },
  { name:"SESKO", meta:{shortened:false}, hint:{age:20,club:"RB Leipzig",country:"Slovenia",position:"ST",trivia:"Young talent"} },
  { name:"HOJLU", meta:{shortened:true,fullName:"Hojlund"}, hint:{age:21,club:"Man United",country:"Denmark",position:"ST",trivia:"Big signing"} },
  { name:"JACKS", meta:{shortened:true,fullName:"Jackson"}, hint:{age:22,club:"Chelsea",country:"Senegal",position:"ST",trivia:"Inconsistent"} },
  { name:"WATKI", meta:{shortened:true,fullName:"Watkins"}, hint:{age:28,club:"Aston Villa",country:"England",position:"ST",trivia:"Goal scorer"} },
  { name:"SOLAN", meta:{shortened:true,fullName:"Solanke"}, hint:{age:26,club:"Bournemouth",country:"England",position:"ST",trivia:"Chelsea academy"} },
  { name:"STERL", meta:{shortened:true,fullName:"Sterling"}, hint:{age:29,club:"Chelsea",country:"England",position:"LW",trivia:"Pep's winger"} },
  { name:"SANCH", meta:{shortened:true,fullName:"Sancho"}, hint:{age:24,club:"Man United",country:"England",position:"RW",trivia:"Dortmund star"} },
  { name:"GREAL", meta:{shortened:true,fullName:"Grealish"}, hint:{age:28,club:"Man City",country:"England",position:"LW",trivia:"British record"} },
  { name:"DOKU", meta:{shortened:false}, hint:{age:21,club:"Man City",country:"Belgium",position:"RW",trivia:"Dribbling king"} },
  { name:"MITOM", meta:{shortened:true,fullName:"Mitoma"}, hint:{age:26,club:"Brighton",country:"Japan",position:"LW",trivia:"Dribbling master"} },
  { name:"KUBO", meta:{shortened:false}, hint:{age:22,club:"Real Sociedad",country:"Japan",position:"RW",trivia:"Japanese Messi"} },
  { name:"CHIES", meta:{shortened:true,fullName:"Chiesa"}, hint:{age:26,club:"Juventus",country:"Italy",position:"LW",trivia:"Euro 2020 hero"} },
  { name:"BOWEN", meta:{shortened:false}, hint:{age:27,club:"West Ham",country:"England",position:"RW",trivia:"Europa hero"} },
  { name:"GORDO", meta:{shortened:true,fullName:"Gordon"}, hint:{age:23,club:"Newcastle",country:"England",position:"LW",trivia:"Pace"} },
  { name:"ISAK", meta:{shortened:false}, hint:{age:24,club:"Newcastle",country:"Sweden",position:"ST",trivia:"Tall striker"} },
  { name:"ENDRK", meta:{shortened:true,fullName:"Endrick"}, hint:{age:17,club:"Real Madrid",country:"Brazil",position:"ST",trivia:"Future star"} },
  { name:"YAMAL", meta:{shortened:false}, hint:{age:16,club:"Barcelona",country:"Spain",position:"RW",trivia:"Youngest debut"} },
  { name:"MAINO", meta:{shortened:true,fullName:"Mainoo"}, hint:{age:19,club:"Man United",country:"England",position:"CM",trivia:"Academy breakout"} },
  { name:"COLWI", meta:{shortened:true,fullName:"Colwill"}, hint:{age:21,club:"Chelsea",country:"England",position:"CB",trivia:"Brighton loan"} },
  { name:"LEWIS", meta:{shortened:false}, hint:{age:19,club:"Man City",country:"England",position:"RB",trivia:"Pep's trust"} },
  { name:"BALDE", meta:{shortened:false}, hint:{age:20,club:"Barcelona",country:"Spain",position:"LB",trivia:"La Masia"} },
  { name:"GARNA", meta:{shortened:true,fullName:"Garnacho"}, hint:{age:19,club:"Man United",country:"Argentina",position:"LW",trivia:"Bicycle kick"} },
  { name:"ELLIO", meta:{shortened:true,fullName:"Elliott"}, hint:{age:21,club:"Liverpool",country:"England",position:"RW",trivia:"Young debut"} },
  { name:"SIMON", meta:{shortened:false}, hint:{age:22,club:"Athletic",country:"Spain",position:"LW",trivia:"Dribbling"} },
  { name:"VERME", meta:{shortened:true,fullName:"Vermeeren"}, hint:{age:19,club:"Atletico",country:"Belgium",position:"CM",trivia:"Young talent"} },
  { name:"PELÉ", meta:{shortened:false}, hint:{age:82,club:"Retired",country:"Brazil",position:"FW",trivia:"3x World Cup winner"} },
  { name:"MARAD", meta:{shortened:true,fullName:"Maradona"}, hint:{age:60,club:"Retired",country:"Argentina",position:"AM",trivia:"Hand of God"} },
  { name:"ZIDAN", meta:{shortened:true,fullName:"Zidane"}, hint:{age:52,club:"Retired",country:"France",position:"AM",trivia:"1998 World Cup hero"} },
  { name:"RONAZ", meta:{shortened:true,fullName:"Ronaldo Nazario"}, hint:{age:47,club:"Retired",country:"Brazil",position:"ST",trivia:"Il Fenomeno"} },
  { name:"HENRY", meta:{shortened:false}, hint:{age:46,club:"Retired",country:"France",position:"FW",trivia:"Arsenal invincibles"} },
  { name:"RONAL", meta:{shortened:true,fullName:"Ronaldinho"}, hint:{age:44,club:"Retired",country:"Brazil",position:"AM",trivia:"2005 Ballon d'Or"} },
  { name:"BECKH", meta:{shortened:true,fullName:"Beckham"}, hint:{age:49,club:"Retired",country:"England",position:"RW",trivia:"Free kick king"} },
  { name:"PIRLO", meta:{shortened:false}, hint:{age:45,club:"Retired",country:"Italy",position:"DM",trivia:"Deep-lying playmaker"} },
  { name:"TOTTI", meta:{shortened:false}, hint:{age:47,club:"Retired",country:"Italy",position:"CF",trivia:"One-club legend"} },
  { name:"SCHOL", meta:{shortened:true,fullName:"Scholes"}, hint:{age:49,club:"Retired",country:"England",position:"CM",trivia:"Man United engine"} },
  { name:"GIGGS", meta:{shortened:false}, hint:{age:50,club:"Retired",country:"Wales",position:"LW",trivia:"Most PL titles"} },
  { name:"GERRD", meta:{shortened:true,fullName:"Gerrard"}, hint:{age:44,club:"Retired",country:"England",position:"CM",trivia:"Istanbul miracle"} },
  { name:"LAMPA", meta:{shortened:true,fullName:"Lampard"}, hint:{age:45,club:"Retired",country:"England",position:"CM",trivia:"Chelsea goals record"} },
  { name:"TERRY", meta:{shortened:false}, hint:{age:43,club:"Retired",country:"England",position:"CB",trivia:"Chelsea captain"} },
  { name:"FERDI", meta:{shortened:true,fullName:"Ferdinand"}, hint:{age:45,club:"Retired",country:"England",position:"CB",trivia:"Man Utd wall"} },
  { name:"VIDIC", meta:{shortened:false}, hint:{age:43,club:"Retired",country:"Serbia",position:"CB",trivia:"Fearless CB"} },
  { name:"COLER", meta:{shortened:true,fullName:"Cole"}, hint:{age:42,club:"Retired",country:"England",position:"LB",trivia:"Best LB of era"} },
  { name:"NEVIL", meta:{shortened:true,fullName:"Neville"}, hint:{age:49,club:"Retired",country:"England",position:"RB",trivia:"Man Utd loyalist"} },
  { name:"KEANE", meta:{shortened:false}, hint:{age:52,club:"Retired",country:"Ireland",position:"CM",trivia:"Man Utd enforcer"} },
  { name:"VIEIR", meta:{shortened:false}, hint:{age:48,club:"Retired",country:"France",position:"CM",trivia:"Arsenal captain"} },
  { name:"KLOSE", meta:{shortened:false}, hint:{age:46,club:"Retired",country:"Germany",position:"ST",trivia:"World Cup top scorer"} },
  { name:"BALLA", meta:{shortened:true,fullName:"Ballack"}, hint:{age:47,club:"Retired",country:"Germany",position:"CM",trivia:"German powerhouse"} },
  { name:"ETOO", meta:{shortened:false}, hint:{age:43,club:"Retired",country:"Cameroon",position:"ST",trivia:"African legend"} },
  { name:"DROG", meta:{shortened:true,fullName:"Drogba"}, hint:{age:46,club:"Retired",country:"Ivory Coast",position:"ST",trivia:"Chelsea clutch king"} },
  { name:"TORRE", meta:{shortened:false}, hint:{age:40,club:"Retired",country:"Spain",position:"ST",trivia:"Euro 2008 hero"} },
  { name:"VILLA", meta:{shortened:false}, hint:{age:42,club:"Retired",country:"Spain",position:"ST",trivia:"Spain top scorer"} },
  { name:"FABRE", meta:{shortened:true,fullName:"Fabregas"}, hint:{age:37,club:"Retired",country:"Spain",position:"CM",trivia:"Pass master"} },
  { name:"CASIL", meta:{shortened:true,fullName:"Casillas"}, hint:{age:43,club:"Retired",country:"Spain",position:"GK",trivia:"San Iker"} },
  { name:"BUTTO", meta:{shortened:true,fullName:"Buffon"}, hint:{age:46,club:"Retired",country:"Italy",position:"GK",trivia:"Gigi the great"} },
  { name:"CANAR", meta:{shortened:true,fullName:"Cannavaro"}, hint:{age:51,club:"Retired",country:"Italy",position:"CB",trivia:"2006 Ballon d'Or"} },
  { name:"NESTA", meta:{shortened:false}, hint:{age:48,club:"Retired",country:"Italy",position:"CB",trivia:"Elegant defender"} },
  { name:"MALDO", meta:{shortened:true,fullName:"Maldini"}, hint:{age:55,club:"Retired",country:"Italy",position:"LB",trivia:"Greatest defender"} },
  { name:"BAREA", meta:{shortened:true,fullName:"Baresi"}, hint:{age:64,club:"Retired",country:"Italy",position:"CB",trivia:"AC Milan legend"} },
  { name:"SHEVI", meta:{shortened:true,fullName:"Shevchenko"}, hint:{age:48,club:"Retired",country:"Ukraine",position:"ST",trivia:"2004 Ballon d'Or"} },
  { name:"BATAN", meta:{shortened:true,fullName:"Batistuta"}, hint:{age:55,club:"Retired",country:"Argentina",position:"ST",trivia:"Batigol"} },
  { name:"ROMAR", meta:{shortened:true,fullName:"Romario"}, hint:{age:58,club:"Retired",country:"Brazil",position:"ST",trivia:"1000 career goals"} },
  { name:"BEBET", meta:{shortened:false}, hint:{age:60,club:"Retired",country:"Brazil",position:"ST",trivia:"Baby celebration"} },
  { name:"RIVAA", meta:{shortened:true,fullName:"Rivaldo"}, hint:{age:52,club:"Retired",country:"Brazil",position:"AM",trivia:"2002 WC winner"} },
  { name:"RIVEN", meta:{shortened:true,fullName:"Rivaldo"}, hint:{age:52,club:"Retired",country:"Brazil",position:"AM",trivia:"Ballon d'Or 1999"} },
  { name:"ROQUE", meta:{shortened:true,fullName:"Roberto Carlos"}, hint:{age:51,club:"Retired",country:"Brazil",position:"LB",trivia:"Free kick physics"} },
  { name:"CAFUS", meta:{shortened:true,fullName:"Cafu"}, hint:{age:54,club:"Retired",country:"Brazil",position:"RB",trivia:"2x WC winner"} },
  { name:"ZAMOR", meta:{shortened:true,fullName:"Zamora"}, hint:{age:40,club:"Retired",country:"Venezuela",position:"ST",trivia:"La Pantera"} },
  { name:"WEAH", meta:{shortened:false}, hint:{age:57,club:"Retired",country:"Liberia",position:"FW",trivia:"1995 Ballon d'Or"} },
  { name:"KLINS", meta:{shortened:true,fullName:"Klinsmann"}, hint:{age:59,club:"Retired",country:"Germany",position:"ST",trivia:"Diving celebration"} },
  { name:"EFFEB", meta:{shortened:true,fullName:"Effenberg"}, hint:{age:56,club:"Retired",country:"Germany",position:"CM",trivia:"UCL hero 2001"} },
  { name:"FIGO", meta:{shortened:false}, hint:{age:51,club:"Retired",country:"Portugal",position:"RW",trivia:"2000 Ballon d'Or"} },
  { name:"OVERM", meta:{shortened:true,fullName:"Overmars"}, hint:{age:51,club:"Retired",country:"Netherlands",position:"LW",trivia:"Arsenal speed"} },
  { name:"BERGK", meta:{shortened:true,fullName:"Bergkamp"}, hint:{age:55,club:"Retired",country:"Netherlands",position:"CF",trivia:"Non-flying Dutchman"} },
  { name:"VBABB", meta:{shortened:true,fullName:"Van Basten"}, hint:{age:60,club:"Retired",country:"Netherlands",position:"ST",trivia:"1988 Euro hero"} },
  { name:"GULLI", meta:{shortened:false}, hint:{age:62,club:"Retired",country:"Netherlands",position:"AM",trivia:"1987 Ballon d'Or"} },
  { name:"RIJKA", meta:{shortened:true,fullName:"Rijkaard"}, hint:{age:62,club:"Retired",country:"Netherlands",position:"DM",trivia:"Ajax legend"} },
  { name:"KOEMA", meta:{shortened:true,fullName:"Koeman"}, hint:{age:61,club:"Retired",country:"Netherlands",position:"CB",trivia:"Attacking sweeper"} },
  { name:"CRUIF", meta:{shortened:true,fullName:"Cruyff"}, hint:{age:68,club:"Retired",country:"Netherlands",position:"FW",trivia:"Total football king"} },
  { name:"PLATI", meta:{shortened:true,fullName:"Platini"}, hint:{age:69,club:"Retired",country:"France",position:"AM",trivia:"3x Ballon d'Or"} },
  { name:"CANTO", meta:{shortened:false}, hint:{age:58,club:"Retired",country:"France",position:"CF",trivia:"King Eric"} },
  { name:"DESAI", meta:{shortened:true,fullName:"Desailly"}, hint:{age:55,club:"Retired",country:"France",position:"CB",trivia:"1998 WC winner"} },
  { name:"BARTH", meta:{shortened:false}, hint:{age:53,club:"Retired",country:"France",position:"GK",trivia:"Shaved head GK"} },
  { name:"THIER", meta:{shortened:true,fullName:"Thuram"}, hint:{age:52,club:"Retired",country:"France",position:"RB",trivia:"France caps record"} },
  { name:"WILTO", meta:{shortened:false}, hint:{age:45,club:"Retired",country:"France",position:"LW",trivia:"Euro 2000 star"} },
  { name:"PIRES", meta:{shortened:false}, hint:{age:50,club:"Retired",country:"France",position:"LW",trivia:"Arsenal invincible"} },
  { name:"LJUNG", meta:{shortened:true,fullName:"Ljungberg"}, hint:{age:47,club:"Retired",country:"Sweden",position:"RW",trivia:"Red hair icon"} },
  { name:"LARSS", meta:{shortened:true,fullName:"Larsson"}, hint:{age:52,club:"Retired",country:"Sweden",position:"ST",trivia:"Celtic legend"} },
  { name:"IBRAH", meta:{shortened:true,fullName:"Ibrahimovic"}, hint:{age:43,club:"Retired",country:"Sweden",position:"ST",trivia:"25 clubs legend"} },
  { name:"SUKER", meta:{shortened:false}, hint:{age:56,club:"Retired",country:"Croatia",position:"ST",trivia:"98 WC top scorer"} },
  { name:"BOBAN", meta:{shortened:false}, hint:{age:56,club:"Retired",country:"Croatia",position:"CM",trivia:"Croatia icon"} },
  { name:"BOBIC", meta:{shortened:false}, hint:{age:53,club:"Retired",country:"Germany",position:"ST",trivia:"Bundesliga star"} },
  { name:"SAMME", meta:{shortened:false}, hint:{age:57,club:"Retired",country:"Germany",position:"SW",trivia:"1996 Ballon d'Or"} },
  { name:"MATTH", meta:{shortened:false}, hint:{age:63,club:"Retired",country:"Germany",position:"CM",trivia:"1990 Ballon d'Or"} },
  { name:"MUELL", meta:{shortened:true,fullName:"Muller G"}, hint:{age:79,club:"Retired",country:"Germany",position:"ST",trivia:"Der Bomber"} },
  { name:"GROBE", meta:{shortened:true,fullName:"Grobbelaar"}, hint:{age:67,club:"Retired",country:"Zimbabwe",position:"GK",trivia:"Spaghetti legs"} },
  { name:"RUSH", meta:{shortened:false}, hint:{age:62,club:"Retired",country:"Wales",position:"ST",trivia:"Liverpool legend"} },
  { name:"DALGL", meta:{shortened:true,fullName:"Dalglish"}, hint:{age:73,club:"Retired",country:"Scotland",position:"CF",trivia:"King Kenny"} },
  { name:"KEEGA", meta:{shortened:true,fullName:"Keegan"}, hint:{age:73,club:"Retired",country:"England",position:"FW",trivia:"2x Ballon d'Or"} },
  { name:"CHARL", meta:{shortened:true,fullName:"Charlton B"}, hint:{age:86,club:"Retired",country:"England",position:"CM",trivia:"1966 WC hero"} },
  { name:"MURPH", meta:{shortened:true,fullName:"Murphy"}, hint:{age:28,club:"Nottm Forest",country:"England",position:"LW",trivia:"PL breakout"} },
  { name:"ZAHA", meta:{shortened:false}, hint:{age:31,club:"Galatasaray",country:"Ivory Coast",position:"LW",trivia:"Palace legend"} },
  { name:"AYEW", meta:{shortened:false}, hint:{age:34,club:"Al-Qadsiah",country:"Ghana",position:"FW",trivia:"Ghana captain"} },
  { name:"AUBAR", meta:{shortened:true,fullName:"Aubameyang"}, hint:{age:34,club:"Marseille",country:"Gabon",position:"ST",trivia:"Pace and goals"} },
  { name:"IGHAL", meta:{shortened:false}, hint:{age:35,club:"Al-Wehda",country:"Nigeria",position:"ST",trivia:"Man Utd dream"} },
  { name:"MAHRE", meta:{shortened:true,fullName:"Mahrez"}, hint:{age:33,club:"Al-Ahli",country:"Algeria",position:"RW",trivia:"Leicester legend"} },
  { name:"BENRA", meta:{shortened:true,fullName:"Benrahma"}, hint:{age:29,club:"Lyon",country:"Algeria",position:"AM",trivia:"Dribble wizard"} },
  { name:"TADIC", meta:{shortened:false}, hint:{age:35,club:"Fenerbahce",country:"Serbia",position:"AM",trivia:"Ajax captain"} },
  { name:"FORBS", meta:{shortened:true,fullName:"Forsberg"}, hint:{age:32,club:"RB Leipzig",country:"Sweden",position:"CM",trivia:"Leipzig starter"} },
  { name:"OLSEN", meta:{shortened:false}, hint:{age:34,club:"AS Roma",country:"Denmark",position:"GK",trivia:"Solid keeper"} },
  { name:"VEDAT", meta:{shortened:true,fullName:"Muriqi"}, hint:{age:30,club:"Mallorca",country:"Kosovo",position:"ST",trivia:"Kosovo hero"} },
  { name:"KALAJ", meta:{shortened:true,fullName:"Kalajdzic"}, hint:{age:26,club:"Wolves",country:"Austria",position:"ST",trivia:"Target man"} },
  { name:"BROJA", meta:{shortened:false}, hint:{age:22,club:"Chelsea",country:"Albania",position:"ST",trivia:"Chelsea striker"} },
  { name:"ASANO", meta:{shortened:false}, hint:{age:29,club:"Bochum",country:"Japan",position:"FW",trivia:"WC goal scorer"} },
  { name:"TOMIY", meta:{shortened:true,fullName:"Tomiyasu"}, hint:{age:25,club:"Arsenal",country:"Japan",position:"RB",trivia:"Japan's best"} },
  { name:"DOAN", meta:{shortened:false}, hint:{age:25,club:"Freiburg",country:"Japan",position:"RW",trivia:"Japan winger"} },
  { name:"MAEDA", meta:{shortened:false}, hint:{age:26,club:"Celtic",country:"Japan",position:"FW",trivia:"Celtic star"} },
  { name:"CCHO", meta:{shortened:true,fullName:"Cho"}, hint:{age:22,club:"Brighton",country:"Korea",position:"ST",trivia:"Korean talent"} },
  { name:"HWANG", meta:{shortened:false}, hint:{age:28,club:"Wolves",country:"Korea",position:"ST",trivia:"Korean star"} },
  { name:"SONGH", meta:{shortened:true,fullName:"Son Heung-min"}, hint:{age:31,club:"Tottenham",country:"Korea",position:"LW",trivia:"PL Golden Boot"} },
  { name:"PARKE", meta:{shortened:true,fullName:"Park Ji-sung"}, hint:{age:43,club:"Retired",country:"Korea",position:"CM",trivia:"Man Utd legend"} },
  { name:"OCHOA", meta:{shortened:false}, hint:{age:38,club:"America",country:"Mexico",position:"GK",trivia:"WC saves king"} },
  { name:"CHIMA", meta:{shortened:true,fullName:"Chicharito"}, hint:{age:36,club:"LA Galaxy",country:"Mexico",position:"ST",trivia:"Quick finisher"} },
  { name:"LOZAR", meta:{shortened:true,fullName:"Lozano"}, hint:{age:29,club:"PSV",country:"Mexico",position:"RW",trivia:"Mexico winger"} },
  { name:"PULSI", meta:{shortened:true,fullName:"Pulisic"}, hint:{age:26,club:"AC Milan",country:"USA",position:"RW",trivia:"Captain America"} },
  { name:"MCKEN", meta:{shortened:true,fullName:"McKennie"}, hint:{age:25,club:"Juventus",country:"USA",position:"CM",trivia:"US dynamo"} },
  { name:"WEAH2", meta:{shortened:true,fullName:"Tim Weah"}, hint:{age:24,club:"Juventus",country:"USA",position:"RW",trivia:"Weah's son"} },
  { name:"REYNA", meta:{shortened:false}, hint:{age:21,club:"Dortmund",country:"USA",position:"AM",trivia:"USMNT hope"} },
  { name:"DEST", meta:{shortened:false}, hint:{age:23,club:"PSV",country:"USA",position:"RB",trivia:"Athletic RB"} },
  { name:"ACUNA", meta:{shortened:false}, hint:{age:32,club:"Sevilla",country:"Argentina",position:"LB",trivia:"Argentine LB"} },
  { name:"DEMPA", meta:{shortened:true,fullName:"De Paul"}, hint:{age:30,club:"Atletico",country:"Argentina",position:"CM",trivia:"World Cup winner"} },
  { name:"PARED", meta:{shortened:false}, hint:{age:30,club:"Roma",country:"Argentina",position:"CDM",trivia:"WC champion"} },
  { name:"CUTIL", meta:{shortened:true,fullName:"Cuti Romero"}, hint:{age:26,club:"Tottenham",country:"Argentina",position:"CB",trivia:"WC hero"} },
  { name:"TAGLI", meta:{shortened:true,fullName:"Tagliafico"}, hint:{age:31,club:"Lyon",country:"Argentina",position:"LB",trivia:"WC winner"} },
  { name:"MOLER", meta:{shortened:true,fullName:"Molina"}, hint:{age:26,club:"Atletico",country:"Argentina",position:"RB",trivia:"WC scorer"} },
  { name:"DYBAL", meta:{shortened:false}, hint:{age:30,club:"Roma",country:"Argentina",position:"CF",trivia:"La Joya"} },
  { name:"ICARD", meta:{shortened:false}, hint:{age:31,club:"Galatasaray",country:"Argentina",position:"ST",trivia:"Penalty specialist"} },
  { name:"HIGUE", meta:{shortened:true,fullName:"Higuain"}, hint:{age:36,club:"Retired",country:"Argentina",position:"ST",trivia:"Serie A goals record"} },
  { name:"PALAC", meta:{shortened:true,fullName:"Papu Gomez"}, hint:{age:36,club:"Monza",country:"Argentina",position:"AM",trivia:"WC winner"} },
  { name:"FERED", meta:{shortened:true,fullName:"Fred"}, hint:{age:31,club:"Fenerbahce",country:"Brazil",position:"CDM",trivia:"Man Utd CDM"} },
  { name:"RAFIN", meta:{shortened:true,fullName:"Raphinha"}, hint:{age:27,club:"Barcelona",country:"Brazil",position:"RW",trivia:"Brazil winger"} },
  { name:"ANTHO", meta:{shortened:true,fullName:"Antony"}, hint:{age:24,club:"Man United",country:"Brazil",position:"RW",trivia:"Spin move icon"} },
  { name:"RODRY", meta:{shortened:true,fullName:"Rodrygo"}, hint:{age:23,club:"Real Madrid",country:"Brazil",position:"RW",trivia:"UCL hero"} },
  { name:"ERIKE", meta:{shortened:true,fullName:"Eder Militao"}, hint:{age:26,club:"Real Madrid",country:"Brazil",position:"CB",trivia:"Brazil CB"} },
  { name:"MARQI", meta:{shortened:true,fullName:"Marquinhos"}, hint:{age:30,club:"PSG",country:"Brazil",position:"CB",trivia:"PSG captain"} },
  { name:"LYCAR", meta:{shortened:true,fullName:"Lucas"}, hint:{age:32,club:"PSG",country:"Brazil",position:"RW",trivia:"PSG winger"} },
  { name:"NEYMA", meta:{shortened:true,fullName:"Neymar"}, hint:{age:32,club:"Al-Hilal",country:"Brazil",position:"LW",trivia:"200M transfer"} },
  { name:"OSCAR", meta:{shortened:false}, hint:{age:32,club:"Shanghai SIPG",country:"Brazil",position:"AM",trivia:"Brazil playmaker"} },
  { name:"DAVID", meta:{shortened:true,fullName:"David Luiz"}, hint:{age:37,club:"Retired",country:"Brazil",position:"CB",trivia:"Wild hair CB"} },
  { name:"THIAG", meta:{shortened:true,fullName:"Thiago Silva"}, hint:{age:39,club:"Fluminense",country:"Brazil",position:"CB",trivia:"Brazil captain"} },
  { name:"HULKB", meta:{shortened:true,fullName:"Hulk"}, hint:{age:37,club:"Atletico Mineiro",country:"Brazil",position:"ST",trivia:"Power striker"} },
  { name:"FRED2", meta:{shortened:true,fullName:"Freddy"}, hint:{age:40,club:"Retired",country:"Brazil",position:"ST",trivia:"Brazil number 9"} },
  { name:"MOURA", meta:{shortened:true,fullName:"Lucas Moura"}, hint:{age:32,club:"Sao Paulo",country:"Brazil",position:"RW",trivia:"UCL semi hero"} },
  { name:"COUTI", meta:{shortened:false}, hint:{age:32,club:"Aston Villa",country:"Brazil",position:"AM",trivia:"Magic Phil"} },
  { name:"FIRMA", meta:{shortened:true,fullName:"Firmino"}, hint:{age:32,club:"Al-Ahli",country:"Brazil",position:"CF",trivia:"No-look goals"} },
  { name:"JINHO", meta:{shortened:true,fullName:"Joelinton"}, hint:{age:28,club:"Newcastle",country:"Brazil",position:"CM",trivia:"Newcastle engine"} },
  { name:"SANDE", meta:{shortened:true,fullName:"Bruno G"}, hint:{age:27,club:"Juventus",country:"Brazil",position:"CDM",trivia:"Juve anchor"} },
  { name:"TELLE", meta:{shortened:true,fullName:"Telles"}, hint:{age:31,club:"Al-Nassr",country:"Brazil",position:"LB",trivia:"Free kick LB"} },
  { name:"REMED", meta:{shortened:true,fullName:"Reinier"}, hint:{age:22,club:"Girona",country:"Brazil",position:"AM",trivia:"Ex-Real Madrid"} },
  { name:"NKUNK", meta:{shortened:true,fullName:"Nkunku"}, hint:{age:26,club:"Chelsea",country:"France",position:"FW",trivia:"Bundesliga POTY"} },
  { name:"CAMAV", meta:{shortened:true,fullName:"Camavinga"}, hint:{age:21,club:"Real Madrid",country:"France",position:"CM",trivia:"Youngest debut"} },
  { name:"TCHOU", meta:{shortened:true,fullName:"Tchouameni"}, hint:{age:24,club:"Real Madrid",country:"France",position:"CDM",trivia:"France future"} },
  { name:"KOUND", meta:{shortened:true,fullName:"Koundé"}, hint:{age:25,club:"Barcelona",country:"France",position:"RB",trivia:"Versatile Frenchman"} },
  { name:"PAVAR", meta:{shortened:false}, hint:{age:28,club:"Inter Milan",country:"France",position:"CB",trivia:"WC hero goal"} },
  { name:"VARAN", meta:{shortened:false}, hint:{age:31,club:"Man United",country:"France",position:"CB",trivia:"4x UCL winner"} },
  { name:"ZOUMA", meta:{shortened:false}, hint:{age:29,club:"West Ham",country:"France",position:"CB",trivia:"Physical CB"} },
  { name:"KOSCI", meta:{shortened:true,fullName:"Koscielny"}, hint:{age:38,club:"Retired",country:"France",position:"CB",trivia:"Arsenal legend"} },
  { name:"LLORI", meta:{shortened:false}, hint:{age:37,club:"MLS",country:"France",position:"GK",trivia:"France captain"} },
  { name:"GIROU", meta:{shortened:false}, hint:{age:37,club:"MLS",country:"France",position:"ST",trivia:"France top scorer"} },
  { name:"BENAT", meta:{shortened:true,fullName:"Benzema Jr"}, hint:{age:19,club:"Lyon",country:"France",position:"ST",trivia:"Son of legend"} },
  { name:"OLIVI", meta:{shortened:true,fullName:"Giroud Jr"}, hint:{age:21,club:"Lyon",country:"France",position:"CM",trivia:"French talent"} },
  { name:"HERNA", meta:{shortened:false}, hint:{age:27,club:"Bayern",country:"France",position:"LB",trivia:"France LB"} },
  { name:"DISAS", meta:{shortened:false}, hint:{age:26,club:"Chelsea",country:"France",position:"CB",trivia:"French wall"} },
  { name:"LAFON", meta:{shortened:true,fullName:"Lafont"}, hint:{age:25,club:"Nantes",country:"France",position:"GK",trivia:"French keeper"} },
  { name:"POGB2", meta:{shortened:true,fullName:"Pogba Paul"}, hint:{age:31,club:"Juventus",country:"France",position:"CM",trivia:"La Pioche"} },
  { name:"RABIO", meta:{shortened:false}, hint:{age:29,club:"Juventus",country:"France",position:"CM",trivia:"Elegant CM"} },
  { name:"CALVE", meta:{shortened:true,fullName:"Calvert-Lewin"}, hint:{age:27,club:"Everton",country:"England",position:"ST",trivia:"Aerial threat"} },
  { name:"BRAFO", meta:{shortened:true,fullName:"Brentford Ivan"}, hint:{age:26,club:"Brentford",country:"Denmark",position:"ST",trivia:"Brentford hero"} },
  { name:"TRORE", meta:{shortened:true,fullName:"Trossard"}, hint:{age:29,club:"Arsenal",country:"Belgium",position:"LW",trivia:"Brighton breakout"} },
  { name:"LUKAK", meta:{shortened:true,fullName:"Lukaku"}, hint:{age:31,club:"Roma",country:"Belgium",position:"ST",trivia:"Powerful striker"} },
  { name:"HAZAR", meta:{shortened:false}, hint:{age:33,club:"Retired",country:"Belgium",position:"LW",trivia:"Chelsea magician"} },
  { name:"MERTO", meta:{shortened:true,fullName:"Mertens"}, hint:{age:37,club:"Galatasaray",country:"Belgium",position:"CF",trivia:"Napoli legend"} },
  { name:"WITSL", meta:{shortened:true,fullName:"Witsel"}, hint:{age:35,club:"Atletico",country:"Belgium",position:"CM",trivia:"Veteran DM"} },
  { name:"DEFOU", meta:{shortened:false}, hint:{age:36,club:"Retired",country:"Belgium",position:"CM",trivia:"Red Devil"} },
  { name:"CAREL", meta:{shortened:true,fullName:"Carrasco"}, hint:{age:31,club:"Atletico",country:"Belgium",position:"LW",trivia:"UCL finalist"} },
  { name:"DEBRU", meta:{shortened:true,fullName:"De Bruyne"}, hint:{age:32,club:"Man City",country:"Belgium",position:"CM",trivia:"World class"} },
  { name:"KOMPA", meta:{shortened:true,fullName:"Kompany"}, hint:{age:38,club:"Retired",country:"Belgium",position:"CB",trivia:"Man City legend"} },
  { name:"ALDER", meta:{shortened:true,fullName:"Alderweireld"}, hint:{age:35,club:"Retired",country:"Belgium",position:"CB",trivia:"Composed CB"} },
  { name:"VERMO", meta:{shortened:true,fullName:"Vertonghen"}, hint:{age:37,club:"Anderlecht",country:"Belgium",position:"CB",trivia:"Tottenham legend"} },
  { name:"MIGNO", meta:{shortened:true,fullName:"Mignolet"}, hint:{age:36,club:"Club Brugge",country:"Belgium",position:"GK",trivia:"Saves specialist"} },
  { name:"TRAPP", meta:{shortened:false}, hint:{age:34,club:"Frankfurt",country:"Germany",position:"GK",trivia:"Europa keeper"} },
  { name:"GNABR", meta:{shortened:false}, hint:{age:29,club:"Bayern",country:"Germany",position:"RW",trivia:"CL 4-goal night"} },
  { name:"SANE", meta:{shortened:false}, hint:{age:28,club:"Bayern",country:"Germany",position:"LW",trivia:"Speed and skill"} },
  { name:"MULLE", meta:{shortened:false}, hint:{age:34,club:"Bayern",country:"Germany",position:"AM",trivia:"Raumdeuter"} },
  { name:"KIMMI", meta:{shortened:false}, hint:{age:29,club:"Bayern",country:"Germany",position:"CDM",trivia:"Modern midfielder"} },
  { name:"GORET", meta:{shortened:true,fullName:"Goretzka"}, hint:{age:29,club:"Bayern",country:"Germany",position:"CM",trivia:"Box-to-box"} },
  { name:"REUS", meta:{shortened:false}, hint:{age:35,club:"MLS",country:"Germany",position:"AM",trivia:"Dortmund legend"} },
  { name:"GOTZE", meta:{shortened:false}, hint:{age:32,club:"Eintracht",country:"Germany",position:"AM",trivia:"2014 WC winner"} },
  { name:"HUMME", meta:{shortened:true,fullName:"Hummels"}, hint:{age:35,club:"Roma",country:"Germany",position:"CB",trivia:"Elegant CB"} },
  { name:"BOSVE", meta:{shortened:true,fullName:"Bosvelt"}, hint:{age:30,club:"Dortmund",country:"Germany",position:"CB",trivia:"Dortmund CB"} },
  { name:"BRAND", meta:{shortened:false}, hint:{age:27,club:"Dortmund",country:"Germany",position:"AM",trivia:"Creative mid"} },
  { name:"SANCH", meta:{shortened:true,fullName:"Sancho Jude"}, hint:{age:24,club:"Dortmund",country:"England",position:"RW",trivia:"Dortmund start"} },
  { name:"MOUKO", meta:{shortened:false}, hint:{age:19,club:"Dortmund",country:"Germany",position:"ST",trivia:"Young prodigy"} },
  { name:"ADEYE", meta:{shortened:false}, hint:{age:22,club:"Dortmund",country:"Germany",position:"LW",trivia:"Speed winger"} },
  { name:"KLOPP", meta:{shortened:false}, hint:{age:57,club:"Retired",country:"Germany",position:"Manager",trivia:"Heavy metal football"} },
  { name:"MOREN", meta:{shortened:false}, hint:{age:31,club:"Villarreal",country:"Spain",position:"LW",trivia:"El Submarino"} },
  { name:"YEREM", meta:{shortened:true,fullName:"Yeremy"}, hint:{age:21,club:"Villarreal",country:"Spain",position:"RW",trivia:"Spain youth"} },
  { name:"FATI", meta:{shortened:false}, hint:{age:21,club:"Barcelona",country:"Spain",position:"LW",trivia:"Ansu Fati"} },
  { name:"TORRE", meta:{shortened:true,fullName:"Ferran Torres"}, hint:{age:24,club:"Barcelona",country:"Spain",position:"FW",trivia:"Versatile attacker"} },
  { name:"GAYA", meta:{shortened:false}, hint:{age:29,club:"Valencia",country:"Spain",position:"LB",trivia:"Valencia captain"} },
  { name:"AZPIL", meta:{shortened:true,fullName:"Azpilicueta"}, hint:{age:34,club:"Atletico",country:"Spain",position:"RB",trivia:"Chelsea legend"} },
  { name:"MARCO", meta:{shortened:true,fullName:"Marcos Alonso"}, hint:{age:33,club:"Barcelona",country:"Spain",position:"LB",trivia:"Attack-minded LB"} },
  { name:"SOLER", meta:{shortened:false}, hint:{age:27,club:"Valencia",country:"Spain",position:"CM",trivia:"Valencia star"} },
  { name:"MEREU", meta:{shortened:true,fullName:"Merino"}, hint:{age:28,club:"Arsenal",country:"Spain",position:"CM",trivia:"Xavi's type"} },
  { name:"SIMON", meta:{shortened:true,fullName:"Unai Simon"}, hint:{age:27,club:"Athletic",country:"Spain",position:"GK",trivia:"Spain number 1"} },
  { name:"LAPOR", meta:{shortened:true,fullName:"Laporte"}, hint:{age:30,club:"Al-Nassr",country:"Spain",position:"CB",trivia:"Man City CB"} },
  { name:"DIEGO", meta:{shortened:true,fullName:"Diego Carlos"}, hint:{age:31,club:"Aston Villa",country:"Brazil",position:"CB",trivia:"Brazil CB"} },
  { name:"FERMI", meta:{shortened:false}, hint:{age:21,club:"Barcelona",country:"Spain",position:"CM",trivia:"La Masia gem"} },
  { name:"GULER", meta:{shortened:false}, hint:{age:19,club:"Real Madrid",country:"Turkey",position:"AM",trivia:"Turkish wonder"} },
  { name:"OSIMH", meta:{shortened:true,fullName:"Osimhen"}, hint:{age:25,club:"Napoli",country:"Nigeria",position:"ST",trivia:"Napoli king"} },
  { name:"LOOKM", meta:{shortened:true,fullName:"Lookman"}, hint:{age:26,club:"Atalanta",country:"Nigeria",position:"LW",trivia:"UCL final hero"} },
  { name:"IWOBI", meta:{shortened:false}, hint:{age:28,club:"Fulham",country:"Nigeria",position:"CM",trivia:"Nigeria star"} },
  { name:"MOFFI", meta:{shortened:false}, hint:{age:27,club:"Nice",country:"Nigeria",position:"ST",trivia:"Ligue 1 goals"} },
  { name:"OLISE", meta:{shortened:false}, hint:{age:22,club:"Bayern",country:"France",position:"RW",trivia:"Crystal Palace star"} },
  { name:"EDOZI", meta:{shortened:false}, hint:{age:21,club:"Man City",country:"England",position:"LW",trivia:"City winger"} },
  { name:"MACCA", meta:{shortened:true,fullName:"McAtee"}, hint:{age:22,club:"Man City",country:"England",position:"AM",trivia:"City prospect"} },
  { name:"ELLIO", meta:{shortened:true,fullName:"Anderson"}, hint:{age:21,club:"Liverpool",country:"Brazil",position:"FW",trivia:"Liverpool winger"} },
  { name:"NUNEZ", meta:{shortened:true,fullName:"Nunez"}, hint:{age:24,club:"Liverpool",country:"Uruguay",position:"ST",trivia:"Force of nature"} },
  { name:"DIOGO", meta:{shortened:false}, hint:{age:27,club:"Liverpool",country:"Portugal",position:"ST",trivia:"Elite striker"} },
  { name:"JOTA", meta:{shortened:false}, hint:{age:27,club:"Liverpool",country:"Portugal",position:"LW",trivia:"Big game player"} },
  { name:"THIAG", meta:{shortened:true,fullName:"Thiago A"}, hint:{age:33,club:"Liverpool",country:"Spain",position:"CM",trivia:"Ball maestro"} },
  { name:"HENDM", meta:{shortened:true,fullName:"Henderson"}, hint:{age:34,club:"Ajax",country:"England",position:"CM",trivia:"Liverpool captain"} },
  { name:"WIJNA", meta:{shortened:false}, hint:{age:34,club:"Roma",country:"Netherlands",position:"CM",trivia:"Big game CM"} },
  { name:"LALLA", meta:{shortened:false}, hint:{age:36,club:"Retired",country:"England",position:"AM",trivia:"Liverpool cult hero"} },
  { name:"COUTN", meta:{shortened:true,fullName:"Coutinho"}, hint:{age:32,club:"Aston Villa",country:"Brazil",position:"AM",trivia:"Little Magician"} },
  { name:"MANE", meta:{shortened:false}, hint:{age:32,club:"Al-Nassr",country:"Senegal",position:"LW",trivia:"AFCON winner"} },
  { name:"BALDE", meta:{shortened:true,fullName:"Baldé"}, hint:{age:34,club:"Retired",country:"Guinea-Bissau",position:"LW",trivia:"Fast winger"} },
  { name:"SARR", meta:{shortened:false}, hint:{age:26,club:"Atletico",country:"Senegal",position:"LW",trivia:"Watford hero"} },
  { name:"DIATT", meta:{shortened:false}, hint:{age:26,club:"Monaco",country:"Senegal",position:"RW",trivia:"Senegal winger"} },
  { name:"KOULI", meta:{shortened:true,fullName:"Koulibaly"}, hint:{age:33,club:"Al-Hilal",country:"Senegal",position:"CB",trivia:"Napoli rock"} },
  { name:"NDOUR", meta:{shortened:false}, hint:{age:28,club:"PSG",country:"Senegal",position:"CDM",trivia:"Physical CM"} },
  { name:"TRAOR", meta:{shortened:false}, hint:{age:28,club:"Wolves",country:"Mali",position:"RW",trivia:"Raw pace"} },
  { name:"DIALL", meta:{shortened:false}, hint:{age:22,club:"Man United",country:"Guinea",position:"LW",trivia:"Young winger"} },
  { name:"CONTÉ", meta:{shortened:false}, hint:{age:27,club:"Tottenham",country:"Ivory Coast",position:"RW",trivia:"CI winger"} },
  { name:"PERIS", meta:{shortened:false}, hint:{age:35,club:"Hajduk Split",country:"Croatia",position:"LW",trivia:"UCL final goal"} },
  { name:"BROZO", meta:{shortened:false}, hint:{age:31,club:"Al Nassr",country:"Croatia",position:"CDM",trivia:"Metronome"} },
  { name:"GVARD", meta:{shortened:true,fullName:"Gvardiol"}, hint:{age:22,club:"Man City",country:"Croatia",position:"LB",trivia:"WC bronze"} },
  { name:"LIVAK", meta:{shortened:true,fullName:"Livakovic"}, hint:{age:28,club:"Fenerbahce",country:"Croatia",position:"GK",trivia:"Penalty savior"} },
  { name:"PASAL", meta:{shortened:true,fullName:"Pasalic"}, hint:{age:29,club:"Atalanta",country:"Croatia",position:"CM",trivia:"Goals from deep"} },
  { name:"VLASI", meta:{shortened:false}, hint:{age:27,club:"Torino",country:"Croatia",position:"AM",trivia:"Creative mid"} },
  { name:"DUMFR", meta:{shortened:true,fullName:"Dumfries"}, hint:{age:28,club:"Inter",country:"Netherlands",position:"RB",trivia:"Wing-back"} },
  { name:"BLIND", meta:{shortened:false}, hint:{age:34,club:"Girona",country:"Netherlands",position:"LB",trivia:"Versatile Dutch"} },
  { name:"DEPAY", meta:{shortened:false}, hint:{age:30,club:"Atletico",country:"Netherlands",position:"FW",trivia:"Memphis"} },
  { name:"WIJNA", meta:{shortened:true,fullName:"Wijnaldum"}, hint:{age:33,club:"Roma",country:"Netherlands",position:"CM",trivia:"Engine CM"} },
  { name:"TIMBE", meta:{shortened:false}, hint:{age:22,club:"Arsenal",country:"Netherlands",position:"CB",trivia:"Ajax rising"} },
  { name:"DRAGU", meta:{shortened:false}, hint:{age:22,club:"Genoa",country:"Romania",position:"CB",trivia:"Young CB"} },
  { name:"POPES", meta:{shortened:false}, hint:{age:58,club:"Retired",country:"Romania",position:"CM",trivia:"Romania legend"} },
  { name:"HAGI", meta:{shortened:false}, hint:{age:59,club:"Retired",country:"Romania",position:"AM",trivia:"Maradona of Carpathians"} },
  { name:"STOIC", meta:{shortened:true,fullName:"Stoichkov"}, hint:{age:58,club:"Retired",country:"Bulgaria",position:"LW",trivia:"94 WC golden boot"} },
  { name:"PENEV", meta:{shortened:false}, hint:{age:57,club:"Retired",country:"Bulgaria",position:"ST",trivia:"Bulgaria striker"} },
  { name:"ZABAL", meta:{shortened:false}, hint:{age:42,club:"Retired",country:"Argentina",position:"RB",trivia:"Man City legend"} },
  { name:"OTAME", meta:{shortened:false}, hint:{age:36,club:"Benfica",country:"Argentina",position:"CB",trivia:"Tough tackler"} },
  { name:"MASCA", meta:{shortened:true,fullName:"Mascherano"}, hint:{age:40,club:"Retired",country:"Argentina",position:"CDM",trivia:"El Jefecito"} },
  { name:"CAMBI", meta:{shortened:true,fullName:"Cambiasso"}, hint:{age:48,club:"Retired",country:"Argentina",position:"CDM",trivia:"Inter legend"} },
  { name:"RIQUE", meta:{shortened:false}, hint:{age:45,club:"Retired",country:"Argentina",position:"CF",trivia:"El Maestro"} },
  { name:"ORTEG", meta:{shortened:false}, hint:{age:52,club:"Retired",country:"Argentina",position:"CF",trivia:"El Burrito"} },
  { name:"CRESP", meta:{shortened:false}, hint:{age:48,club:"Retired",country:"Argentina",position:"ST",trivia:"Two UCL goals"} },
  { name:"SAVIO", meta:{shortened:false}, hint:{age:43,club:"Retired",country:"Argentina",position:"ST",trivia:"El Conejo"} },
  { name:"VERON", meta:{shortened:false}, hint:{age:49,club:"Retired",country:"Argentina",position:"CM",trivia:"La Brujita"} },
  { name:"ZANET", meta:{shortened:true,fullName:"Zanetti"}, hint:{age:51,club:"Retired",country:"Argentina",position:"RB",trivia:"Inter legend"} },
  { name:"AYALA", meta:{shortened:false}, hint:{age:52,club:"Retired",country:"Argentina",position:"CB",trivia:"El Ratón"} },
  { name:"RECOB", meta:{shortened:false}, hint:{age:47,club:"Retired",country:"Uruguay",position:"LW",trivia:"El Chino"} },
  { name:"FORDE", meta:{shortened:true,fullName:"Forlán"}, hint:{age:45,club:"Retired",country:"Uruguay",position:"ST",trivia:"WC golden ball"} },
  { name:"MUSLE", meta:{shortened:false}, hint:{age:38,club:"Galatasaray",country:"Uruguay",position:"GK",trivia:"Uruguay stopper"} },
  { name:"VALVE", meta:{shortened:false}, hint:{age:25,club:"Real Madrid",country:"Uruguay",position:"CM",trivia:"Fede machine"} },
  { name:"ARRES", meta:{shortened:true,fullName:"Arreese"}, hint:{age:27,club:"RB Leipzig",country:"Uruguay",position:"RW",trivia:"Uruguay winger"} },
  { name:"GIMEN", meta:{shortened:false}, hint:{age:29,club:"Atletico",country:"Uruguay",position:"CB",trivia:"Powerful CB"} },
  { name:"GODÍN", meta:{shortened:false}, hint:{age:38,club:"Retired",country:"Uruguay",position:"CB",trivia:"Atletico wall"} },
  { name:"FUCIL", meta:{shortened:false}, hint:{age:39,club:"Peñarol",country:"Uruguay",position:"RB",trivia:"Uruguay veteran"} },
  { name:"VIDAL", meta:{shortened:false}, hint:{age:36,club:"Atletico Paranaense",country:"Chile",position:"CM",trivia:"King Arturo"} },
  { name:"ALEXI", meta:{shortened:false}, hint:{age:35,club:"MLS",country:"Chile",position:"LW",trivia:"Energiser bunny"} },
  { name:"BRAVO", meta:{shortened:false}, hint:{age:41,club:"Betis",country:"Chile",position:"GK",trivia:"Man City backup"} },
  { name:"MEDEL", meta:{shortened:false}, hint:{age:36,club:"Boca Juniors",country:"Chile",position:"CDM",trivia:"El Pitbull"} },
  { name:"DIAZ", meta:{shortened:false}, hint:{age:27,club:"Liverpool",country:"Colombia",position:"LW",trivia:"Luis Diaz"} },
  { name:"BORRE", meta:{shortened:false}, hint:{age:28,club:"Frankfurt",country:"Colombia",position:"ST",trivia:"Copa winner"} },
  { name:"CUADR", meta:{shortened:true,fullName:"Cuadrado"}, hint:{age:36,club:"Inter",country:"Colombia",position:"RW",trivia:"Tricky winger"} },
  { name:"FALCA", meta:{shortened:false}, hint:{age:38,club:"Rayo Vallecano",country:"Colombia",position:"ST",trivia:"El Tigre"} },
  { name:"JAMES", meta:{shortened:false}, hint:{age:33,club:"Rayo Vallecano",country:"Colombia",position:"AM",trivia:"WC goal of tournament"} },
  { name:"OSPIN", meta:{shortened:false}, hint:{age:36,club:"Al-Qadsiah",country:"Colombia",position:"GK",trivia:"Shot stopper"} },
  { name:"CABAL", meta:{shortened:true,fullName:"Caballero"}, hint:{age:43,club:"Retired",country:"Argentina",position:"GK",trivia:"Penalty specialist"} },
  { name:"ROMER", meta:{shortened:false}, hint:{age:36,club:"Retired",country:"Argentina",position:"GK",trivia:"2014 WC hero"} },
  { name:"SORIA", meta:{shortened:false}, hint:{age:26,club:"Atletico",country:"Spain",position:"CM",trivia:"Spain youth"} },
  { name:"PEDRI", meta:{shortened:true,fullName:"Pedri"}, hint:{age:21,club:"Barcelona",country:"Spain",position:"CM",trivia:"La Masia star"} },
  { name:"BARCO", meta:{shortened:false}, hint:{age:21,club:"PSG",country:"France",position:"LW",trivia:"PSG winger"} },
  { name:"DOUE", meta:{shortened:false}, hint:{age:19,club:"PSG",country:"France",position:"AM",trivia:"Rennes star"} },
  { name:"MUKIE", meta:{shortened:false}, hint:{age:26,club:"PSG",country:"France",position:"RB",trivia:"Versatile RB"} },
  { name:"ZAIRE", meta:{shortened:true,fullName:"Zaire-Emery"}, hint:{age:18,club:"PSG",country:"France",position:"CM",trivia:"Teen prodigy"} },
  { name:"UGART", meta:{shortened:false}, hint:{age:23,club:"PSG",country:"Uruguay",position:"CDM",trivia:"Intense tackler"} },
  { name:"VITIN", meta:{shortened:false}, hint:{age:24,club:"PSG",country:"Portugal",position:"CM",trivia:"Technical CM"} },
  { name:"NUNO", meta:{shortened:true,fullName:"Nuno Mendes"}, hint:{age:22,club:"PSG",country:"Portugal",position:"LB",trivia:"Speedy LB"} },
  { name:"RUBEN", meta:{shortened:true,fullName:"Ruben Neves"}, hint:{age:27,club:"Al-Hilal",country:"Portugal",position:"CDM",trivia:"Wolves legend"} },
  { name:"RAFA", meta:{shortened:true,fullName:"Rafa Silva"}, hint:{age:31,club:"Benfica",country:"Portugal",position:"RW",trivia:"Portugal winger"} },
  { name:"SEMED", meta:{shortened:false}, hint:{age:30,club:"Wolves",country:"Portugal",position:"RB",trivia:"Spain pro"} },
  { name:"PEPE", meta:{shortened:false}, hint:{age:41,club:"Retired",country:"Portugal",position:"CB",trivia:"Enforcer CB"} },
  { name:"COENT", meta:{shortened:true,fullName:"Coentrao"}, hint:{age:36,club:"Retired",country:"Portugal",position:"LB",trivia:"Real Madrid LB"} },
  { name:"MOUTI", meta:{shortened:false}, hint:{age:38,club:"Retired",country:"Portugal",position:"CM",trivia:"Wolves elder"} },
  { name:"DECO", meta:{shortened:false}, hint:{age:47,club:"Retired",country:"Portugal",position:"AM",trivia:"Barcelona gem"} },
  { name:"PAULE", meta:{shortened:false}, hint:{age:52,club:"Retired",country:"Portugal",position:"ST",trivia:"Portugal top scorer"} },
  { name:"EUSEB", meta:{shortened:false}, hint:{age:71,club:"Retired",country:"Portugal",position:"FW",trivia:"Black Panther"} },
  { name:"DZEKO", meta:{shortened:false}, hint:{age:38,club:"Fenerbahce",country:"Bosnia",position:"ST",trivia:"Man City goals"} },
  { name:"PIANI", meta:{shortened:true,fullName:"Pjanic"}, hint:{age:34,club:"Sharjah",country:"Bosnia",position:"CM",trivia:"Elegant passer"} },
  { name:"IBRIS", meta:{shortened:true,fullName:"Ibrisimovic"}, hint:{age:20,club:"Man City",country:"Sweden",position:"ST",trivia:"Zlatan's son"} },
  { name:"DIER", meta:{shortened:false}, hint:{age:30,club:"Bayern",country:"England",position:"CB",trivia:"Spurs stopper"} },
  { name:"ROMER", meta:{shortened:true,fullName:"Romero"}, hint:{age:26,club:"Tottenham",country:"Argentina",position:"CB",trivia:"Ferocious CB"} },
  { name:"BENTA", meta:{shortened:true,fullName:"Bentancur"}, hint:{age:27,club:"Tottenham",country:"Uruguay",position:"CM",trivia:"Composed CM"} },
  { name:"BISOU", meta:{shortened:true,fullName:"Bissouma"}, hint:{age:27,club:"Tottenham",country:"Mali",position:"CDM",trivia:"Brighton gem"} },
  { name:"KULU", meta:{shortened:true,fullName:"Kulusevski"}, hint:{age:24,club:"Tottenham",country:"Sweden",position:"RW",trivia:"Dortmund loan"} },
  { name:"RICHA", meta:{shortened:true,fullName:"Richarlison"}, hint:{age:27,club:"Tottenham",country:"Brazil",position:"ST",trivia:"Bicycle kick"} },
  { name:"HOJBJ", meta:{shortened:false}, hint:{age:28,club:"Tottenham",country:"Denmark",position:"CDM",trivia:"Spurs engine"} },
  { name:"LLORE", meta:{shortened:true,fullName:"Llorentea"}, hint:{age:29,club:"Tottenham",country:"Spain",position:"CM",trivia:"Sevilla grad"} },
  { name:"FERNA", meta:{shortened:true,fullName:"Fernandes B"}, hint:{age:30,club:"Man United",country:"Portugal",position:"CM",trivia:"Goals and assists"} },
  { name:"ANTOT", meta:{shortened:true,fullName:"Antony T"}, hint:{age:24,club:"Man United",country:"Brazil",position:"RW",trivia:"80M purchase"} },
  { name:"PELLI", meta:{shortened:true,fullName:"Pellegrini"}, hint:{age:28,club:"Real Betis",country:"Spain",position:"CM",trivia:"Betis maestro"} },
  { name:"MORAT", meta:{shortened:true,fullName:"Morata"}, hint:{age:31,club:"Atletico",country:"Spain",position:"ST",trivia:"Euro 2024 winner"} },
  { name:"ASENS", meta:{shortened:true,fullName:"Asensio"}, hint:{age:28,club:"PSG",country:"Spain",position:"RW",trivia:"Real Madrid impact"} },
  { name:"ISCO", meta:{shortened:false}, hint:{age:32,club:"Sevilla",country:"Spain",position:"AM",trivia:"Dribble king"} },
  { name:"DANIL", meta:{shortened:false}, hint:{age:32,club:"Nottm Forest",country:"Brazil",position:"RB",trivia:"Man City RB"} },
  { name:"GUEDE", meta:{shortened:false}, hint:{age:27,club:"Benfica",country:"Portugal",position:"LW",trivia:"Valencia star"} },
  { name:"JOAO", meta:{shortened:true,fullName:"João Felix"}, hint:{age:24,club:"Barcelona",country:"Portugal",position:"FW",trivia:"Golden Boy 2019"} },
  { name:"CONCE", meta:{shortened:true,fullName:"Conceição F"}, hint:{age:21,club:"Juventus",country:"Portugal",position:"RW",trivia:"FC's son"} },
  { name:"GONCA", meta:{shortened:true,fullName:"Goncalo Ramos"}, hint:{age:23,club:"PSG",country:"Portugal",position:"ST",trivia:"WC hattrick"} },
  { name:"CHANS", meta:{shortened:true,fullName:"Chancel Mbemba"}, hint:{age:30,club:"Marseille",country:"Congo",position:"CB",trivia:"Marseille rock"} },
  { name:"NZOLA", meta:{shortened:false}, hint:{age:27,club:"Fiorentina",country:"Angola",position:"ST",trivia:"Serie A goals"} },
  { name:"AMRAB", meta:{shortened:true,fullName:"Amrabat"}, hint:{age:27,club:"Man United",country:"Morocco",position:"CDM",trivia:"WC star"} },
  { name:"ZIYEC", meta:{shortened:false}, hint:{age:31,club:"Galatasaray",country:"Morocco",position:"AM",trivia:"Dribble and vision"} },
  { name:"OUNAH", meta:{shortened:false}, hint:{age:23,club:"Marseille",country:"Morocco",position:"CM",trivia:"WC breakout"} },
  { name:"MAZRA", meta:{shortened:false}, hint:{age:26,club:"Bayern",country:"Morocco",position:"RB",trivia:"Ajax RB"} },
  { name:"BONO", meta:{shortened:false}, hint:{age:33,club:"Sevilla",country:"Morocco",position:"GK",trivia:"WC penalty hero"} },
  { name:"SAISS", meta:{shortened:false}, hint:{age:33,club:"Besiktas",country:"Morocco",position:"CB",trivia:"Morocco captain"} },
  { name:"AGUER", meta:{shortened:false}, hint:{age:28,club:"West Ham",country:"Morocco",position:"CB",trivia:"WC star"} },
  { name:"AMALL", meta:{shortened:true,fullName:"Amar Alla"}, hint:{age:30,club:"Al-Feiha",country:"Saudi Arabia",position:"CM",trivia:"Saudi captain"} },
  { name:"SALEM", meta:{shortened:true,fullName:"Salem Al-Dawsari"}, hint:{age:32,club:"Al-Hilal",country:"Saudi Arabia",position:"LW",trivia:"WC goal vs Argentina"} },
  { name:"KANNO", meta:{shortened:false}, hint:{age:30,club:"Al-Shabab",country:"Saudi Arabia",position:"CM",trivia:"Saudi mid"} },
  { name:"VOLLA", meta:{shortened:false}, hint:{age:32,club:"Monaco",country:"Germany",position:"ST",trivia:"Bundesliga goal scorer"} },
  { name:"DIABY", meta:{shortened:false}, hint:{age:27,club:"Al-Ittihad",country:"France",position:"LW",trivia:"Leverkusen flyer"} },
  { name:"SCHIC", meta:{shortened:false}, hint:{age:28,club:"Leverkusen",country:"Czech Rep",position:"ST",trivia:"Euro top scorer"} },
  { name:"SOUCE", meta:{shortened:false}, hint:{age:29,club:"West Ham",country:"Czech Rep",position:"CM",trivia:"Goals from box"} },
  { name:"KOVAR", meta:{shortened:false}, hint:{age:24,club:"Bayer Leverkusen",country:"Czech Rep",position:"GK",trivia:"Man Utd loan"} },
  { name:"BENES", meta:{shortened:false}, hint:{age:25,club:"Gladbach",country:"Czech Rep",position:"CM",trivia:"Silky passer"} },
  { name:"DAMSG", meta:{shortened:false}, hint:{age:24,club:"Brentford",country:"Denmark",position:"AM",trivia:"Euro 2020 star"} },
  { name:"BRAIT", meta:{shortened:false}, hint:{age:33,club:"Espanyol",country:"Denmark",position:"ST",trivia:"Barca striker"} },
  { name:"CHRIS", meta:{shortened:false}, hint:{age:28,club:"Barcelona",country:"Denmark",position:"CB",trivia:"Chelsea to Barca"} },
  { name:"MAEHL", meta:{shortened:false}, hint:{age:27,club:"Atalanta",country:"Denmark",position:"LB",trivia:"Dynamic LB"} },
  { name:"ERIKS", meta:{shortened:false}, hint:{age:32,club:"Man United",country:"Denmark",position:"CM",trivia:"Comeback king"} },
  { name:"STIND", meta:{shortened:true,fullName:"Stindl"}, hint:{age:35,club:"Retired",country:"Germany",position:"AM",trivia:"Gladbach gem"} },
  { name:"VLAHO", meta:{shortened:false}, hint:{age:24,club:"Juventus",country:"Serbia",position:"ST",trivia:"Serie A top scorer"} },
  { name:"MITRO", meta:{shortened:false}, hint:{age:29,club:"Al-Hilal",country:"Serbia",position:"ST",trivia:"Header king"} },
  { name:"MILIN", meta:{shortened:false}, hint:{age:29,club:"Al-Hilal",country:"Serbia",position:"CM",trivia:"Complete midfielder"} },
  { name:"TADIC", meta:{shortened:true,fullName:"Tadic S"}, hint:{age:35,club:"Fenerbahce",country:"Serbia",position:"AM",trivia:"Ajax captain"} },
  { name:"SPAJI", meta:{shortened:false}, hint:{age:26,club:"Man United",country:"Serbia",position:"CB",trivia:"Monaco CB"} },
  { name:"STOJK", meta:{shortened:false}, hint:{age:59,club:"Retired",country:"Serbia",position:"AM",trivia:"Yugoslavia legend"} },
  { name:"LAZOV", meta:{shortened:false}, hint:{age:33,club:"Hellas Verona",country:"Serbia",position:"LB",trivia:"Verona regular"} },
  { name:"JOVIC", meta:{shortened:false}, hint:{age:26,club:"AC Milan",country:"Serbia",position:"ST",trivia:"Real Madrid flop"} },
  { name:"KOSTA", meta:{shortened:true,fullName:"Kostic"}, hint:{age:31,club:"Juventus",country:"Serbia",position:"LW",trivia:"Cross king"} },
  { name:"TARKO", meta:{shortened:true,fullName:"Tarkovic"}, hint:{age:28,club:"Spartak",country:"Serbia",position:"ST",trivia:"SPL star"} },
  { name:"MULLE", meta:{shortened:true,fullName:"Muller T"}, hint:{age:34,club:"Bayern",country:"Germany",position:"SS",trivia:"Most Bundesliga assists"} },
  { name:"IMMOB", meta:{shortened:true,fullName:"Immobile"}, hint:{age:34,club:"Besiktas",country:"Italy",position:"ST",trivia:"Capocannoniere"} },
  { name:"INSIG", meta:{shortened:false}, hint:{age:33,club:"Toronto FC",country:"Italy",position:"LW",trivia:"Napoli captain"} },
  { name:"VERRA", meta:{shortened:true,fullName:"Verratti"}, hint:{age:31,club:"Al Arabi",country:"Italy",position:"CM",trivia:"Mini Pirlo"} },
  { name:"BARON", meta:{shortened:true,fullName:"Baroni"}, hint:{age:26,club:"Sassuolo",country:"Italy",position:"CM",trivia:"Young Italian"} },
  { name:"LOCAT", meta:{shortened:false}, hint:{age:26,club:"Juventus",country:"Italy",position:"CDM",trivia:"Euro 2020 hero"} },
  { name:"TONAL", meta:{shortened:false}, hint:{age:24,club:"Newcastle",country:"Italy",position:"CM",trivia:"New Pirlo"} },
  { name:"BASTO", meta:{shortened:false}, hint:{age:25,club:"Inter",country:"Italy",position:"CB",trivia:"Ball-playing CB"} },
  { name:"DARMI", meta:{shortened:false}, hint:{age:34,club:"Inter",country:"Italy",position:"RB",trivia:"Inter full-back"} },
  { name:"DIMA", meta:{shortened:true,fullName:"Di Marco"}, hint:{age:26,club:"Inter",country:"Italy",position:"LB",trivia:"Cross specialist"} },
  { name:"BARET", meta:{shortened:true,fullName:"Barella"}, hint:{age:27,club:"Inter",country:"Italy",position:"CM",trivia:"Box-to-box"} },
  { name:"FRATT", meta:{shortened:true,fullName:"Frattesi"}, hint:{age:24,club:"Inter",country:"Italy",position:"CM",trivia:"Goalscoring CM"} },
  { name:"SCALV", meta:{shortened:false}, hint:{age:20,club:"Atalanta",country:"Italy",position:"CB",trivia:"Italy's future"} },
  { name:"KEAN", meta:{shortened:false}, hint:{age:24,club:"Juventus",country:"Italy",position:"ST",trivia:"Juve striker"} },
  { name:"ZANIO", meta:{shortened:false}, hint:{age:25,club:"Galatasaray",country:"Italy",position:"AM",trivia:"Roma talent"} },
  { name:"PELLE", meta:{shortened:false}, hint:{age:28,club:"Roma",country:"Italy",position:"AM",trivia:"Roma captain"} },
  { name:"THURA", meta:{shortened:true,fullName:"Thuram M"}, hint:{age:27,club:"Inter",country:"France",position:"ST",trivia:"Lilian's son"} },
  { name:"DALLI", meta:{shortened:false}, hint:{age:23,club:"Toulouse",country:"Netherlands",position:"ST",trivia:"Dutch striker"} },
  { name:"BROBB", meta:{shortened:false}, hint:{age:22,club:"Ajax",country:"Netherlands",position:"ST",trivia:"Ajax power"} },
  { name:"CLASI", meta:{shortened:false}, hint:{age:32,club:"Feyenoord",country:"Netherlands",position:"CDM",trivia:"Netherlands DM"} },
  { name:"BERGH", meta:{shortened:false}, hint:{age:32,club:"Ajax",country:"Netherlands",position:"AM",trivia:"Ajax star"} },
  { name:"KOOPM", meta:{shortened:false}, hint:{age:26,club:"Atalanta",country:"Netherlands",position:"CM",trivia:"AZ star"} },
  { name:"VEERM", meta:{shortened:false}, hint:{age:25,club:"PSV",country:"Netherlands",position:"CM",trivia:"PSV engine"} },
  { name:"LANG", meta:{shortened:false}, hint:{age:25,club:"PSV",country:"Netherlands",position:"RW",trivia:"Dutch winger"} },
  { name:"BAKAY", meta:{shortened:false}, hint:{age:30,club:"Retired",country:"France",position:"CDM",trivia:"Physical CDM"} },
  { name:"MENDE", meta:{shortened:true,fullName:"Mendes P"}, hint:{age:25,club:"Porto",country:"Portugal",position:"LB",trivia:"Portugal LB"} },
  { name:"ADAN", meta:{shortened:false}, hint:{age:36,club:"Sporting CP",country:"Spain",position:"GK",trivia:"Sporting GK"} },
  { name:"MARTI", meta:{shortened:false}, hint:{age:25,club:"Benfica",country:"Portugal",position:"LW",trivia:"Benfica winger"} },
  { name:"GELSO", meta:{shortened:false}, hint:{age:29,club:"Sporting CP",country:"Portugal",position:"RW",trivia:"Portuguese spark"} },
  { name:"TAREM", meta:{shortened:false}, hint:{age:32,club:"Inter",country:"Iran",position:"ST",trivia:"Porto legend"} },
  { name:"JAHAN", meta:{shortened:false}, hint:{age:31,club:"Feyenoord",country:"Iran",position:"RW",trivia:"PL debut scorer"} },
  { name:"GHAFO", meta:{shortened:false}, hint:{age:36,club:"Al-Gaish",country:"Iran",position:"LW",trivia:"Iran winger"} },
  { name:"QUAIS", meta:{shortened:false}, hint:{age:30,club:"Copenhagen",country:"Sweden",position:"ST",trivia:"Palermo grad"} },
  { name:"ELANG", meta:{shortened:false}, hint:{age:22,club:"Nottm Forest",country:"Sweden",position:"RW",trivia:"Man Utd youth"} },
  { name:"ISAKA", meta:{shortened:true,fullName:"Isak A"}, hint:{age:24,club:"Newcastle",country:"Sweden",position:"ST",trivia:"Real Sociedad gem"} },
  { name:"FORSB", meta:{shortened:true,fullName:"Forsberg E"}, hint:{age:32,club:"Leipzig",country:"Sweden",position:"CM",trivia:"Leipzig icon"} },
  { name:"EXTRA", meta:{shortened:true,fullName:"Svensson"}, hint:{age:28,club:"Bayer Leverkusen",country:"Sweden",position:"LB",trivia:"Solid LB"} },
  { name:"SKOV", meta:{shortened:false}, hint:{age:28,club:"Bochum",country:"Denmark",position:"LB",trivia:"Denmark LB"} },
  { name:"NORGA", meta:{shortened:false}, hint:{age:30,club:"Brentford",country:"Denmark",position:"CDM",trivia:"Brentford rock"} },
  { name:"DELAN", meta:{shortened:false}, hint:{age:32,club:"Hoffenheim",country:"Denmark",position:"CM",trivia:"Denmark engine"} },
  { name:"HJULM", meta:{shortened:false}, hint:{age:24,club:"Sporting CP",country:"Denmark",position:"CDM",trivia:"Denmark DM"} },
  { name:"BOILE", meta:{shortened:false}, hint:{age:32,club:"Copenhagen",country:"Denmark",position:"LB",trivia:"Denmark LB"} },
  { name:"GYTKJ", meta:{shortened:false}, hint:{age:33,club:"Nice",country:"Denmark",position:"ST",trivia:"Header specialist"} },
];
